"""Blender background script for editable core/front Weapon Concept starter assets."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

import bpy
from mathutils import Vector


MATERIALS = {
    "MAT_primary": ((0.035, 0.055, 0.08, 1.0), 0.72, 0.34),
    "MAT_secondary": ((0.12, 0.16, 0.21, 1.0), 0.58, 0.42),
    "MAT_accent": ((0.62, 0.018, 0.012, 1.0), 0.42, 0.30),
}


@dataclass(frozen=True)
class Part:
    name: str
    center_mm: tuple[float, float, float]
    size_mm: tuple[float, float, float]
    material: str
    bevel_mm: float = 2.0


@dataclass(frozen=True)
class Connector:
    connector_id: str
    slot: str
    connector_type: str
    position_mm: tuple[float, float, float]


@dataclass(frozen=True)
class Module:
    module_id: str
    category: str
    parts: tuple[Part, ...]
    connectors: tuple[Connector, ...]


MODULES = (
    Module(
        "module_core_shell_01",
        "core_shell",
        (
            Part("main_body", (0, 0, 0), (100, 46, 40), "MAT_primary", 4.0),
            Part("upper_spine", (-4, 21, 0), (76, 10, 30), "MAT_secondary", 2.5),
            Part("lower_keel", (-10, -21, 0), (48, 9, 32), "MAT_secondary", 2.0),
            Part("side_plate_a", (25, 0, 20), (28, 26, 3), "MAT_accent", 1.0),
            Part("side_plate_b", (-28, 0, -20), (20, 22, 3), "MAT_accent", 1.0),
        ),
        (
            Connector("connector_core_front", "core.front", "shell_mount", (-50, 0, 0)),
            Connector("connector_core_rear", "core.rear", "rear_mount", (50, 0, 0)),
            Connector("connector_core_grip", "core.grip", "grip_mount", (14, -23, 0)),
            Connector("connector_core_top", "core.top", "top_mount", (0, 23, 0)),
            Connector("connector_core_side", "core.side", "side_mount", (0, 0, 20)),
            Connector("connector_core_lower", "core.lower", "lower_mount", (-12, -23, 0)),
            Connector("connector_core_storage", "core.storage", "storage_mount", (30, -23, 0)),
            Connector("connector_core_armor", "core.armor", "armor_mount", (0, 0, -20)),
        ),
    ),
    Module(
        "module_front_shell_01",
        "front_shell",
        (
            Part("main_wedge", (-31, 0, 0), (62, 32, 32), "MAT_primary", 3.0),
            Part("upper_rib", (-36, 16, 0), (42, 6, 27), "MAT_secondary", 1.5),
            Part("nose_cap", (-60, 5, 0), (14, 22, 28), "MAT_secondary", 2.5),
            Part("accent_fin", (-44, 0, 17), (20, 15, 2.5), "MAT_accent", 0.8),
        ),
        (Connector("connector_front_01_core", "front.core", "shell_mount", (0, 0, 0)),),
    ),
    Module(
        "module_front_shell_02",
        "front_shell",
        (
            Part("main_wedge", (-37, 0, 0), (74, 28, 38), "MAT_primary", 4.0),
            Part("upper_bridge", (-34, 15, 0), (40, 8, 32), "MAT_secondary", 2.0),
            Part("nose_block", (-68, 7, 0), (16, 18, 30), "MAT_secondary", 2.0),
            Part("lower_step", (-20, -15, 0), (32, 6, 30), "MAT_accent", 1.0),
            Part("tip_accent", (-61, 0, -20), (16, 12, 2.5), "MAT_accent", 0.8),
        ),
        (Connector("connector_front_02_core", "front.core", "shell_mount", (0, 0, 0)),),
    ),
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(_script_args())
    output_root = args.output_root.expanduser().resolve()
    repository_root = Path(__file__).resolve().parents[2]
    committed_pack_root = repository_root / "assets" / "module-packs"
    if output_root.is_relative_to(committed_pack_root):
        raise RuntimeError("starter output cannot target committed assets/module-packs")
    if output_root.exists() and any(output_root.iterdir()):
        if not args.force:
            raise RuntimeError("starter output is not empty; use --force for a deliberate rebuild")
        shutil.rmtree(output_root)
    (output_root / "LICENSES").mkdir(parents=True, exist_ok=True)
    license_text = (
        "SPDX-License-Identifier: LicenseRef-ForgeCAD-Authoring-Starter\n"
        "Editable non-functional concept/game/film-prop starter generated by ForgeCAD.\n"
        "Not final art and not manufacturing documentation.\n"
    )
    (output_root / "LICENSES" / "PACK.txt").write_text(license_text, encoding="utf-8")
    entries = [_build_module(output_root, module, license_text) for module in MODULES]
    pack = {
        "schema_version": "ModulePackManifest@1",
        "pack_id": "pack_weapon_concept_v1",
        "profile_id": "profile_weapon_concept_v1",
        "name": "Weapon Concept v1 Blender authoring starter",
        "version": "0.1.0",
        "description": (
            "Editable Blender starter for three non-functional concept/game/film-prop modules; "
            "requires human art review before promotion."
        ),
        "intended_uses": ["visual_asset", "game_asset", "film_prop", "non_functional_display"],
        "non_functional_only": True,
        "units": "millimeter",
        "up_axis": "Y",
        "forward_axis": "-Z",
        "handedness": "right",
        "license": {
            "spdx_expression": "LicenseRef-ForgeCAD-Authoring-Starter",
            "license_path": "LICENSES/PACK.txt",
        },
        "modules": entries,
    }
    _write_json(output_root / "pack.json", pack)


def _build_module(output_root: Path, module: Module, license_text: str) -> dict[str, str]:
    _reset_scene()
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0
    scene.render.engine = "BLENDER_EEVEE_NEXT"
    scene.render.resolution_x = 512
    scene.render.resolution_y = 512
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.film_transparent = True
    collection = bpy.data.collections.new(f"MOD_{module.module_id}")
    scene.collection.children.link(collection)
    materials = _create_materials()
    mesh_objects = []
    for index, part in enumerate(module.parts, start=1):
        mesh_objects.append(_create_part(module.module_id, index, part, materials, collection))
    for connector in module.connectors:
        _create_connector(connector, collection)
    _create_render_rig(mesh_objects)
    scene["forgecad_authoring_metadata"] = json.dumps(
        {
            "schema_version": "ForgeCADBlenderAuthoring@1",
            "module_id": module.module_id,
            "category": module.category,
            "pack_id": "pack_weapon_concept_v1",
            "asset_id": f"asset_{module.module_id.removeprefix('module_')}",
            "connectors": [
                {
                    "connector_id": connector.connector_id,
                    "slot": connector.slot,
                    "connector_type": connector.connector_type,
                    "scale_range": [0.9, 1.1],
                    "exclusive": True,
                }
                for connector in module.connectors
            ],
        },
        sort_keys=True,
    )

    module_root = output_root / "modules" / module.module_id
    source_root = output_root / "sources"
    module_root.mkdir(parents=True, exist_ok=True)
    source_root.mkdir(parents=True, exist_ok=True)
    bpy.ops.wm.save_as_mainfile(filepath=str(source_root / f"{module.module_id}.blend"))

    for item in bpy.context.selected_objects:
        item.select_set(False)
    # Connector empties remain in the editable .blend source. Runtime Connector truth
    # lives in module.json, so GLB exports only identity-transform mesh objects.
    for item in mesh_objects:
        item.select_set(True)
    bpy.context.view_layer.objects.active = mesh_objects[0]
    glb_path = module_root / "model.glb"
    bpy.ops.export_scene.gltf(
        filepath=str(glb_path),
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True,
        export_texcoords=True,
        export_normals=True,
        export_materials="EXPORT",
    )

    scene.render.filepath = str(module_root / "thumbnail.png")
    bpy.ops.render.render(write_still=True)
    bounds_mm = _bounds_mm(mesh_objects)
    triangle_count = sum(sum(max(0, len(poly.vertices) - 2) for poly in obj.data.polygons) for obj in mesh_objects)
    payload = glb_path.read_bytes()
    manifest = {
        "schema_version": "ModuleAssetManifest@1",
        "module_id": module.module_id,
        "pack_id": "pack_weapon_concept_v1",
        "category": module.category,
        "asset_id": f"asset_{module.module_id.removeprefix('module_')}",
        "sha256": hashlib.sha256(payload).hexdigest(),
        "bounds_mm": bounds_mm,
        "triangle_count": triangle_count,
        "material_slots": list(MATERIALS),
        "connectors": [
            {
                "connector_id": connector.connector_id,
                "slot": connector.slot,
                "connector_type": connector.connector_type,
                "transform": {
                    "position": list(connector.position_mm),
                    "rotation": [0, 0, 0],
                    "scale": [1, 1, 1],
                },
                "scale_range": [0.9, 1.1],
                "exclusive": True,
            }
            for connector in module.connectors
        ],
    }
    _write_json(module_root / "module.json", manifest)
    (module_root / "LICENSE.txt").write_text(license_text, encoding="utf-8")
    relative_root = f"modules/{module.module_id}"
    return {
        "module_id": module.module_id,
        "manifest_path": f"{relative_root}/module.json",
        "glb_path": f"{relative_root}/model.glb",
        "thumbnail_path": f"{relative_root}/thumbnail.png",
        "license_path": f"{relative_root}/LICENSE.txt",
        "lod": "LOD0",
    }


def _reset_scene() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)


def _create_materials() -> dict[str, bpy.types.Material]:
    result = {}
    for name, (color, metallic, roughness) in MATERIALS.items():
        material = bpy.data.materials.new(name)
        material.diffuse_color = color
        material.use_nodes = True
        principled = material.node_tree.nodes.get("Principled BSDF")
        principled.inputs["Base Color"].default_value = color
        principled.inputs["Metallic"].default_value = metallic
        principled.inputs["Roughness"].default_value = roughness
        result[name] = material
    return result


def _create_part(module_id, index, part, materials, collection):
    bpy.ops.mesh.primitive_cube_add(size=1)
    obj = bpy.context.object
    for owner in tuple(obj.users_collection):
        owner.objects.unlink(obj)
    collection.objects.link(obj)
    obj.name = f"GEO_{module_id}_LOD0_{index:02d}"
    obj.data.name = f"MESH_{module_id}_LOD0_{index:02d}"
    obj.location = Vector(value / 1000 for value in part.center_mm)
    obj.dimensions = Vector(value / 1000 for value in part.size_mm)
    obj.data.materials.append(materials[part.material])
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    bevel = obj.modifiers.new("Bevel", "BEVEL")
    bevel.width = part.bevel_mm / 1000
    bevel.segments = 3
    bpy.ops.object.modifier_apply(modifier=bevel.name)
    triangulate = obj.modifiers.new("Triangulate", "TRIANGULATE")
    bpy.ops.object.modifier_apply(modifier=triangulate.name)
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.uv.smart_project(angle_limit=math.radians(66), island_margin=0.02)
    bpy.ops.object.mode_set(mode="OBJECT")
    obj.data.uv_layers.active.name = "UV0"
    obj.select_set(False)
    return obj


def _create_connector(connector, collection):
    obj = bpy.data.objects.new(f"CON_{connector.connector_id}", None)
    collection.objects.link(obj)
    obj.empty_display_type = "ARROWS"
    obj.empty_display_size = 0.008
    obj.location = Vector(value / 1000 for value in connector.position_mm)
    return obj


def _create_render_rig(objects) -> None:
    minimum, maximum = _bounds(objects)
    center = (minimum + maximum) * 0.5
    extent = max(maximum - minimum)
    bpy.ops.object.camera_add(location=center + Vector((extent * 1.8, -extent * 2.2, extent * 1.4)))
    camera = bpy.context.object
    camera.data.type = "ORTHO"
    camera.data.ortho_scale = extent * 1.65
    camera.rotation_euler = _look_at(camera.location, center)
    bpy.context.scene.camera = camera
    for location, energy, size in (
        (center + Vector((extent, -extent, extent * 2)), 700, extent * 3),
        (center + Vector((-extent, -extent * 0.5, extent)), 450, extent * 2),
    ):
        bpy.ops.object.light_add(type="AREA", location=location)
        light = bpy.context.object
        light.data.energy = energy
        light.data.shape = "DISK"
        light.data.size = size
        light.rotation_euler = _look_at(light.location, center)
    bpy.context.scene.world.color = (0.012, 0.018, 0.028)


def _look_at(origin, target):
    return (target - origin).to_track_quat("-Z", "Y").to_euler()


def _bounds(objects):
    points = [obj.matrix_world @ Vector(corner) for obj in objects for corner in obj.bound_box]
    return (
        Vector(min(point[axis] for point in points) for axis in range(3)),
        Vector(max(point[axis] for point in points) for axis in range(3)),
    )


def _bounds_mm(objects):
    minimum, maximum = _bounds(objects)
    return [round((maximum[axis] - minimum[axis]) * 1000, 4) for axis in range(3)]


def _write_json(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _script_args():
    return sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []


if __name__ == "__main__":
    main()
