import { useMemo } from 'react'
import type { AgentSelectionCardProps } from './AgentSelectionCard'

type UseCadWorkbenchPanelAgentSelectionCardPresentationInput = {
  agentBlockoutSegmentation: AgentSelectionCardProps['segmentation'] | null
} & Omit<AgentSelectionCardProps, 'segmentation'>

export function useCadWorkbenchPanelAgentSelectionCardPresentation(
  input: UseCadWorkbenchPanelAgentSelectionCardPresentationInput,
): AgentSelectionCardProps | null {
  const {
    agentBlockoutSegmentation,
    agentAssetVersion,
    activeAgentAssetVersion,
    selectedPart,
    selectedPartId,
    partDisplay,
    isSelectedPartLocked,
    isExternalGlbReference,
    isSnapshotActionPending,
    agentAssetChangeSet,
    agentComponentCandidates,
    agentStructureSuggestions,
    structureSuggestionUnavailableMessage,
    semanticProportions,
    editAssistLoading,
    blockoutPreviewPresentation,
    onSelectPart,
    onPreviewEdit,
    onSaveSelectedComponent,
    onReplaceComponent,
    onPreviewStructureSuggestion,
    onSetPartDisplay,
    onInspectAsset,
    onRejectChange,
    onConfirmChange,
    onOpenSurfaceAdornment,
    surfaceAdornmentDisabled,
    surfaceAdornmentDetail,
  } = input

  return useMemo(
    () => agentBlockoutSegmentation
      ? {
        segmentation: agentBlockoutSegmentation,
        agentAssetVersion,
        activeAgentAssetVersion,
        selectedPart,
        selectedPartId,
        partDisplay,
        isSelectedPartLocked,
        isExternalGlbReference,
        isSnapshotActionPending,
        agentAssetChangeSet,
        agentComponentCandidates,
        agentStructureSuggestions,
        structureSuggestionUnavailableMessage,
        semanticProportions,
        editAssistLoading,
        blockoutPreviewPresentation,
        onSelectPart,
        onPreviewEdit,
        onSaveSelectedComponent,
        onReplaceComponent,
        onPreviewStructureSuggestion,
        onSetPartDisplay,
        onInspectAsset,
        onRejectChange,
        onConfirmChange,
        onOpenSurfaceAdornment,
        surfaceAdornmentDisabled,
        surfaceAdornmentDetail,
      }
      : null,
    [
      agentBlockoutSegmentation,
      agentAssetVersion,
      activeAgentAssetVersion,
      selectedPart,
      selectedPartId,
      partDisplay,
      isSelectedPartLocked,
      isExternalGlbReference,
      isSnapshotActionPending,
      agentAssetChangeSet,
      agentComponentCandidates,
      agentStructureSuggestions,
      structureSuggestionUnavailableMessage,
      semanticProportions,
      editAssistLoading,
      blockoutPreviewPresentation,
      onSelectPart,
      onPreviewEdit,
      onSaveSelectedComponent,
      onReplaceComponent,
      onPreviewStructureSuggestion,
      onSetPartDisplay,
      onInspectAsset,
      onRejectChange,
      onConfirmChange,
      onOpenSurfaceAdornment,
      surfaceAdornmentDisabled,
      surfaceAdornmentDetail,
    ],
  )
}
