#!/usr/bin/env python3
"""Export FastAPI OpenAPI and generated desktop API component types."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List

from generate_schema_types import ROOT, ts_type


OPENAPI_OUT = ROOT / "packages" / "weapon-spec" / "generated" / "openapi.json"
API_TS_OUT = ROOT / "apps" / "desktop" / "src" / "shared" / "generated" / "api-types.ts"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    openapi = build_openapi()
    outputs = {
        OPENAPI_OUT: json.dumps(openapi, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        API_TS_OUT: render_api_types(openapi),
    }

    if args.check:
        stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            for path in stale:
                print(f"stale generated artifact: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("openapi generated artifacts ok")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


def build_openapi() -> Dict[str, Any]:
    with tempfile.TemporaryDirectory(prefix="wushen_openapi_") as tmp:
        sys.path.insert(0, str(ROOT / "apps" / "agent"))
        os.environ.setdefault("WUSHEN_LIBRARY_ROOT", str(Path(tmp) / "WushenForgeLibrary"))
        os.environ.setdefault("WUSHEN_MIGRATIONS_DIR", str(ROOT / "migrations"))
        from wushen_agent.main import create_app

        return create_app().openapi()


def render_api_types(openapi: Dict[str, Any]) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines: List[str] = [
        "/* eslint-disable */",
        "// Generated by scripts/export_openapi.py. Do not edit by hand.",
        "",
    ]
    for name in sorted(schemas):
        lines.append(f"export type {name} = {ts_type(schemas[name], required=True)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


if __name__ == "__main__":
    sys.exit(main())
