#!/usr/bin/env python3
"""Generate lightweight TS/Python schema artifacts from JSON Schema contracts."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_TARGETS = (
    (
        ROOT / "packages" / "weapon-spec" / "schemas",
        ROOT / "packages" / "weapon-spec" / "generated" / "types.ts",
        ROOT / "apps" / "agent" / "wushen_agent" / "generated" / "schema_registry.py",
    ),
    (
        ROOT / "packages" / "concept-spec" / "schemas",
        ROOT / "packages" / "concept-spec" / "generated" / "types.ts",
        ROOT / "apps" / "agent" / "forgecad_agent" / "generated" / "concept_schema_registry.py",
    ),
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    outputs: Dict[Path, str] = {}
    for schema_dir, typescript_out, python_out in CONTRACT_TARGETS:
        schemas = load_schemas(schema_dir)
        outputs[typescript_out] = render_typescript(schemas)
        outputs[python_out] = render_python_registry(schemas)

    if args.check:
        stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            for path in stale:
                print(f"stale generated artifact: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("schema generated artifacts ok")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


def load_schemas(schema_dir: Path) -> Dict[str, Dict[str, Any]]:
    schemas = {
        path.name: json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(schema_dir.glob("*.json"))
    }
    if "common.schema.json" not in schemas:
        raise RuntimeError(f"contract package is missing common.schema.json: {schema_dir}")
    return schemas


def render_typescript(schemas: Dict[str, Dict[str, Any]]) -> str:
    lines: List[str] = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_schema_types.py. Do not edit by hand.",
        "",
    ]

    common_defs = schemas["common.schema.json"].get("$defs", {})
    for name, schema in common_defs.items():
        lines.append(f"export type {pascal_case(name)} = {ts_type(schema, required=True)}")
        lines.append("")

    for file_name, schema in schemas.items():
        if file_name == "common.schema.json":
            continue
        type_name = schema.get("title") or pascal_case(file_name.replace(".schema.json", ""))
        lines.append(f"export type {type_name} = {ts_type(schema, required=True)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def ts_type(schema: Dict[str, Any], *, required: bool) -> str:
    if "$ref" in schema:
        return ref_to_ts(schema["$ref"])
    if "const" in schema:
        return literal(schema["const"])
    if "enum" in schema:
        return " | ".join(literal(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item, required=True) for item in schema["anyOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(ts_primitive(value) if value != "object" else "Record<string, unknown>" for value in schema_type)
    if schema_type == "object" or "properties" in schema:
        return object_type(schema)
    if schema_type == "array":
        return f"Array<{ts_type(schema.get('items', {}), required=True)}>"
    if schema_type:
        return ts_primitive(schema_type)
    return "unknown"


def object_type(schema: Dict[str, Any]) -> str:
    properties = schema.get("properties", {})
    if not properties:
        return "Record<string, unknown>"
    required = set(schema.get("required", []))
    parts = ["{"]
    for name, prop_schema in properties.items():
        optional = "" if name in required else "?"
        parts.append(f"  {json.dumps(name)}{optional}: {ts_type(prop_schema, required=name in required)}")
    parts.append("}")
    return "\n".join(parts)


def ref_to_ts(ref: str) -> str:
    if ref.startswith("#/components/schemas/"):
        return ref.rsplit("/", 1)[-1]
    if ref.startswith("#/$defs/"):
        return pascal_case(ref.rsplit("/", 1)[-1])
    if ref.startswith("common.schema.json#/$defs/"):
        return pascal_case(ref.rsplit("/", 1)[-1])
    if ref.endswith(".schema.json"):
        return pascal_case(ref.replace(".schema.json", ""))
    return "unknown"


def ts_primitive(schema_type: str) -> str:
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema_type, "unknown")


def literal(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    return json.dumps(value, ensure_ascii=False)


def render_python_registry(schemas: Dict[str, Dict[str, Any]]) -> str:
    canonical = {name: canonical_json(schema) for name, schema in schemas.items()}
    hashes = {name: hashlib.sha256(payload.encode("utf-8")).hexdigest() for name, payload in canonical.items()}
    return (
        "# Generated by scripts/generate_schema_types.py. Do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        "import json\n"
        "from typing import Any, Dict\n\n"
        "SCHEMA_HASHES: Dict[str, str] = json.loads(r'''\n"
        f"{json.dumps(hashes, ensure_ascii=False, indent=2, sort_keys=True)}\n"
        "''')\n\n"
        "SCHEMAS: Dict[str, Dict[str, Any]] = json.loads(r'''\n"
        f"{json.dumps(schemas, ensure_ascii=False, indent=2, sort_keys=True)}\n"
        "''')\n"
    )


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def pascal_case(value: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", value)
    return "".join(part[:1].upper() + part[1:] for part in parts if part)


if __name__ == "__main__":
    sys.exit(main())
